services:
  landing:
    build:
      context: landing
      dockerfile: Dockerfile
    ports:
      - "4321:4321"
    volumes:
      - ./landing:/app
  api:
    build:
      context: api
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./api:/api