services:
  landing:
    build:
      context: landing
      dockerfile: Dockerfile
    ports:
      - "4321:4321"
    volumes:
      - ./landing:/app
  api:
    build:
      context: api
      dockerfile: Dockerfile
    environment:
      NODE_ENV: dev
    ports:
      - "3000:3000"
    volumes:
      - ./api:/api
  db:
    image: mysql:8.4
    ports:
      - "3306:3306"
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: mydb
        MYSQL_USER: user
        MYSQL_PASSWORD: password
    volumes:
        - ./db/data:/var/lib/mysql